trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Install dependencies (Robot Framework, Selenium Library)
  - script: |
      pip install --upgrade robotframework-seleniumlibrary 
    displayName: 'Install Robot Framework and dependencies'

  # 2. Run the Robot Framework tests.
  - script: |
      robot --output test_results/output.xml --log test_results/log.html --report test_results/report.html kim.robot
    displayName: 'Run Original Kim Tests'

  - script: |
      robot --output test_results/output_new_kim_test.xml --log test_results/log_new_kim_test.html --report test_results/report_new_kim_test.html new_tests/tests/kim.robot
    displayName: 'Run Refactored Kim Tests'

  # 3. Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/test_results/'
      artifactName: 'robot-reports'
    displayName: 'Publish Robot Framework Reports'

  - task: PublishPipelineArtifact@2
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/new_tests/test_results/'
      artifactName: 'robot-reports'
    displayName: 'Publish Robot Framework Reports'
