trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Install dependencies (Robot Framework and Selenium)
  - script: |
      pip install --upgrade robotframework-seleniumlibrary 
    displayName: 'Install Python dependencies'

  # 2. Run the Robot Framework tests.
  - script: |
      robot  --output output.xml --log log.html --report report.html tests.robot
    displayName: 'Run Robot Framework Tests'
