trigger:
  - dev-branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Install dependencies (Robot Framework, Selenium Library)
  - script: |
      pip install --upgrade robotframework-seleniumlibrary 
    displayName: 'Install Robot Framework and dependencies'

  # 2. Run the Robot Framework tests.
  - script: |
      robot --output tests/output_kim_test.xml --log test_results/log_kim_test.html --report test_results/report_kim_test.html tests/kim.robot
    displayName: 'Run Kim Tests'

  # 3. Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports'
    displayName: 'Publish Robot Framework Reports'
